language: php
sudo: false
php:
  - '7.4.0'
cache:
  directories:
      - $HOME/.composer/cache/files
      - $HOME/symfony-bridge/.phpunit

services:
  - mysql

install:
  - composer install
  - php bin/console doctrine:database:create --env=test
  - php bin/console doctrine:schema:update --force --env=test

script:
  - php bin/phpunit